import fs from 'fs';
import matter from "gray-matter";
import Markdown from "markdown-to-jsx"
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'About - Ferry Dermawan',
    description: 'Generated by create next app',
};

const getArticleContent = () => {
    const file = "contents/about.mdx";
    const content = fs.readFileSync(file, "utf8");
    const matterResult = matter(content);

    return matterResult;
}

export default function Page() {
    const article = getArticleContent();
    return (
        <article className="prose prose-base lg:prose-base xl:prose-lg max-w-none mt-16">
            <Markdown>{article.content}</Markdown>
        </article>
    )
}
